---
version: "2.0"
services:
  flux:
    image: registry.hf.space/black-forest-labs-flux-1-schnell:latest
    expose:
      - port: 7860
        as: 7860
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - python app.py
profiles:
  compute:
    flux:
      resources:
        cpu:
          units: 4
        memory:
          size: 32Gi
        storage:
          - size: 50Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtxa6000
  placement:
    dcloud:
      pricing:
        flux:
          denom: uakt
          amount: 1000
deployment:
  flux:
    dcloud:
      profile: flux
      count: 1
